# Generated by Django 4.2.4 on 2023-09-08 09:12

import apps.product.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_brand_is_active_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='order',
            field=apps.product.fields.OrderField(blank=True, null=True),
        ),
    ]
